/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

import javax.swing.JFrame;

/**
 *
 * @author MSI2
 */
public class Chu_Quan extends javax.swing.JFrame {

    private String TaiKhoan;

    public String getTaiKhoan() 
    {
        return TaiKhoan;
    }

    public void setTaiKhoan(String TaiKhoan) {
        this.TaiKhoan = TaiKhoan;
    }
    
    public Chu_Quan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        bg_trangchu = new javax.swing.JPanel();
        text_trangchu = new javax.swing.JLabel();
        icon_trangchu = new javax.swing.JLabel();
        bg_banhang = new javax.swing.JPanel();
        icon_banhang = new javax.swing.JLabel();
        button_banhang = new javax.swing.JButton();
        bg_nv = new javax.swing.JPanel();
        icon_nhanvien = new javax.swing.JLabel();
        button_nhanvien = new javax.swing.JButton();
        bg_nhaphang = new javax.swing.JPanel();
        icon_nhaphang = new javax.swing.JLabel();
        button_nhaphang = new javax.swing.JButton();
        bg_khachhang = new javax.swing.JPanel();
        icon_khachhang = new javax.swing.JLabel();
        button_khachhang = new javax.swing.JButton();
        bg_ban = new javax.swing.JPanel();
        icon_ban = new javax.swing.JLabel();
        button_ban = new javax.swing.JButton();
        bg_thucdon = new javax.swing.JPanel();
        icon_thucdon = new javax.swing.JLabel();
        button_thucdon = new javax.swing.JButton();
        bg_nguyenlieu = new javax.swing.JPanel();
        icon_nguyenlieu = new javax.swing.JLabel();
        button_nguyenlieu = new javax.swing.JButton();
        bg_thongke = new javax.swing.JPanel();
        icon_thongke = new javax.swing.JLabel();
        button_thongke = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bg_thoat = new javax.swing.JPanel();
        button_dangxuat = new javax.swing.JButton();
        bg_chuquan = new javax.swing.JPanel();
        bg_cafeomely = new javax.swing.JPanel();
        icon_cafe = new javax.swing.JLabel();
        bg_cafe_cake = new javax.swing.JPanel();
        image_cafe_cake = new javax.swing.JLabel();
        bg_address = new javax.swing.JPanel();
        text_cafeomely1 = new javax.swing.JLabel();
        icon_cafe1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_trangchu.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu.setText("Trang chủ");

        icon_trangchu.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_home_32px.png"))); // NOI18N
        icon_trangchu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu.setOpaque(true);

        javax.swing.GroupLayout bg_trangchuLayout = new javax.swing.GroupLayout(bg_trangchu);
        bg_trangchu.setLayout(bg_trangchuLayout);
        bg_trangchuLayout.setHorizontalGroup(
            bg_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_trangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(bg_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_trangchuLayout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(text_trangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        bg_trangchuLayout.setVerticalGroup(
            bg_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_trangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(bg_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(text_trangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        sidepane.add(bg_trangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        bg_banhang.setBackground(new java.awt.Color(85, 65, 118));

        icon_banhang.setBackground(new java.awt.Color(54, 33, 89));
        icon_banhang.setForeground(new java.awt.Color(255, 255, 255));
        icon_banhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_banhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_shop_26px.png"))); // NOI18N
        icon_banhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_banhang.setOpaque(true);

        button_banhang.setBackground(new java.awt.Color(54, 33, 89));
        button_banhang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_banhang.setForeground(new java.awt.Color(255, 255, 255));
        button_banhang.setText("Bán hàng");
        button_banhang.setOpaque(false);
        button_banhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_banhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_banhangLayout = new javax.swing.GroupLayout(bg_banhang);
        bg_banhang.setLayout(bg_banhangLayout);
        bg_banhangLayout.setHorizontalGroup(
            bg_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_banhangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_banhangLayout.setVerticalGroup(
            bg_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_banhang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_banhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_banhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 310, 40));

        bg_nv.setBackground(new java.awt.Color(85, 65, 118));

        icon_nhanvien.setBackground(new java.awt.Color(54, 33, 89));
        icon_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        icon_nhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_management_24px.png"))); // NOI18N
        icon_nhanvien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_nhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon_nhanvien.setInheritsPopupMenu(false);
        icon_nhanvien.setOpaque(true);

        button_nhanvien.setBackground(new java.awt.Color(54, 33, 89));
        button_nhanvien.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        button_nhanvien.setText("Nhân viên");
        button_nhanvien.setOpaque(false);
        button_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nhanvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_nvLayout = new javax.swing.GroupLayout(bg_nv);
        bg_nv.setLayout(bg_nvLayout);
        bg_nvLayout.setHorizontalGroup(
            bg_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_nvLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bg_nvLayout.setVerticalGroup(
            bg_nvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_nhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 40));

        bg_nhaphang.setBackground(new java.awt.Color(85, 65, 118));

        icon_nhaphang.setBackground(new java.awt.Color(54, 33, 89));
        icon_nhaphang.setForeground(new java.awt.Color(255, 255, 255));
        icon_nhaphang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_nhaphang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_partially_shipped_24px.png"))); // NOI18N
        icon_nhaphang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_nhaphang.setMaximumSize(new java.awt.Dimension(34, 40));
        icon_nhaphang.setMinimumSize(new java.awt.Dimension(34, 40));
        icon_nhaphang.setOpaque(true);

        button_nhaphang.setBackground(new java.awt.Color(54, 33, 89));
        button_nhaphang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_nhaphang.setForeground(new java.awt.Color(255, 255, 255));
        button_nhaphang.setText("Nhập hàng");
        button_nhaphang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_nhaphang.setOpaque(false);
        button_nhaphang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nhaphangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_nhaphangLayout = new javax.swing.GroupLayout(bg_nhaphang);
        bg_nhaphang.setLayout(bg_nhaphangLayout);
        bg_nhaphangLayout.setHorizontalGroup(
            bg_nhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_nhaphangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_nhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_nhaphangLayout.setVerticalGroup(
            bg_nhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_nhaphang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(button_nhaphang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_nhaphang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 310, 40));

        bg_khachhang.setBackground(new java.awt.Color(85, 65, 118));

        icon_khachhang.setBackground(new java.awt.Color(54, 33, 89));
        icon_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        icon_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_customer_26px_1.png"))); // NOI18N
        icon_khachhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_khachhang.setOpaque(true);

        button_khachhang.setBackground(new java.awt.Color(54, 33, 89));
        button_khachhang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_khachhang.setForeground(new java.awt.Color(255, 255, 255));
        button_khachhang.setText("Khách hàng");
        button_khachhang.setOpaque(false);
        button_khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_khachhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_khachhangLayout = new javax.swing.GroupLayout(bg_khachhang);
        bg_khachhang.setLayout(bg_khachhangLayout);
        bg_khachhangLayout.setHorizontalGroup(
            bg_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_khachhangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bg_khachhangLayout.setVerticalGroup(
            bg_khachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_khachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_khachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 310, 40));

        bg_ban.setBackground(new java.awt.Color(85, 65, 118));

        icon_ban.setBackground(new java.awt.Color(54, 33, 89));
        icon_ban.setForeground(new java.awt.Color(255, 255, 255));
        icon_ban.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_ban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_table_26px.png"))); // NOI18N
        icon_ban.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_ban.setOpaque(true);

        button_ban.setBackground(new java.awt.Color(54, 33, 89));
        button_ban.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_ban.setForeground(new java.awt.Color(255, 255, 255));
        button_ban.setText("Bàn");
        button_ban.setOpaque(false);
        button_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_banActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_banLayout = new javax.swing.GroupLayout(bg_ban);
        bg_ban.setLayout(bg_banLayout);
        bg_banLayout.setHorizontalGroup(
            bg_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_banLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_banLayout.setVerticalGroup(
            bg_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_ban, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_ban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_ban, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 310, 40));

        bg_thucdon.setBackground(new java.awt.Color(85, 65, 118));

        icon_thucdon.setBackground(new java.awt.Color(54, 33, 89));
        icon_thucdon.setForeground(new java.awt.Color(255, 255, 255));
        icon_thucdon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_thucdon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_cutlery_26px.png"))); // NOI18N
        icon_thucdon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_thucdon.setOpaque(true);

        button_thucdon.setBackground(new java.awt.Color(54, 33, 89));
        button_thucdon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thucdon.setForeground(new java.awt.Color(255, 255, 255));
        button_thucdon.setText("Thực đơn");
        button_thucdon.setActionCommand("Thực dơn");
        button_thucdon.setOpaque(false);
        button_thucdon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thucdonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thucdonLayout = new javax.swing.GroupLayout(bg_thucdon);
        bg_thucdon.setLayout(bg_thucdonLayout);
        bg_thucdonLayout.setHorizontalGroup(
            bg_thucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_thucdonLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_thucdon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_thucdon, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bg_thucdonLayout.setVerticalGroup(
            bg_thucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_thucdon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_thucdon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_thucdon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 310, 40));

        bg_nguyenlieu.setBackground(new java.awt.Color(85, 65, 118));

        icon_nguyenlieu.setBackground(new java.awt.Color(54, 33, 89));
        icon_nguyenlieu.setForeground(new java.awt.Color(255, 255, 255));
        icon_nguyenlieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_nguyenlieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_food_as_resources_30px.png"))); // NOI18N
        icon_nguyenlieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_nguyenlieu.setMaximumSize(new java.awt.Dimension(34, 40));
        icon_nguyenlieu.setMinimumSize(new java.awt.Dimension(34, 40));
        icon_nguyenlieu.setOpaque(true);

        button_nguyenlieu.setBackground(new java.awt.Color(54, 33, 89));
        button_nguyenlieu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_nguyenlieu.setForeground(new java.awt.Color(255, 255, 255));
        button_nguyenlieu.setText("Nguyên liệu");
        button_nguyenlieu.setActionCommand("Bàn");
        button_nguyenlieu.setOpaque(false);
        button_nguyenlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nguyenlieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_nguyenlieuLayout = new javax.swing.GroupLayout(bg_nguyenlieu);
        bg_nguyenlieu.setLayout(bg_nguyenlieuLayout);
        bg_nguyenlieuLayout.setHorizontalGroup(
            bg_nguyenlieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_nguyenlieuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_nguyenlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_nguyenlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        bg_nguyenlieuLayout.setVerticalGroup(
            bg_nguyenlieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_nguyenlieu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_nguyenlieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_nguyenlieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 310, 40));

        bg_thongke.setBackground(new java.awt.Color(85, 65, 118));

        icon_thongke.setBackground(new java.awt.Color(54, 33, 89));
        icon_thongke.setForeground(new java.awt.Color(255, 255, 255));
        icon_thongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_statistics_26px.png"))); // NOI18N
        icon_thongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_thongke.setOpaque(true);

        button_thongke.setBackground(new java.awt.Color(54, 33, 89));
        button_thongke.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thongke.setForeground(new java.awt.Color(255, 255, 255));
        button_thongke.setText("Thống kê");
        button_thongke.setOpaque(false);
        button_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thongkeLayout = new javax.swing.GroupLayout(bg_thongke);
        bg_thongke.setLayout(bg_thongkeLayout);
        bg_thongkeLayout.setHorizontalGroup(
            bg_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_thongkeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_thongkeLayout.setVerticalGroup(
            bg_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(button_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(bg_thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 310, 40));

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(54, 33, 89));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_manager_26px.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Chủ Quán");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 110, 1));

        sidepane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 620));

        bg_thoat.setBackground(new java.awt.Color(85, 65, 118));

        button_dangxuat.setBackground(new java.awt.Color(255, 255, 255));
        button_dangxuat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_dangxuat.setForeground(new java.awt.Color(204, 0, 0));
        button_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_logout_rounded_left_24px_1.png"))); // NOI18N
        button_dangxuat.setText("Đăng Xuất");
        button_dangxuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thoatLayout = new javax.swing.GroupLayout(bg_thoat);
        bg_thoat.setLayout(bg_thoatLayout);
        bg_thoatLayout.setHorizontalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addContainerGap(743, Short.MAX_VALUE)
                .addComponent(button_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_thoatLayout.setVerticalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(button_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bg.add(bg_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 890, 60));

        bg_chuquan.setBackground(new java.awt.Color(54, 33, 89));
        bg_chuquan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_cafeomely.setBackground(new java.awt.Color(85, 65, 118));

        icon_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafeomelyLayout = new javax.swing.GroupLayout(bg_cafeomely);
        bg_cafeomely.setLayout(bg_cafeomelyLayout);
        bg_cafeomelyLayout.setHorizontalGroup(
            bg_cafeomelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_cafeomelyLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(icon_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(641, 641, 641))
        );
        bg_cafeomelyLayout.setVerticalGroup(
            bg_cafeomelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg_chuquan.add(bg_cafeomely, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 870, -1));

        bg_cafe_cake.setBackground(new java.awt.Color(54, 33, 89));

        image_cafe_cake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_cafe_cake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/quan_cafe.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafe_cakeLayout = new javax.swing.GroupLayout(bg_cafe_cake);
        bg_cafe_cake.setLayout(bg_cafe_cakeLayout);
        bg_cafe_cakeLayout.setHorizontalGroup(
            bg_cafe_cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_cafe_cakeLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(image_cafe_cake)
                .addGap(112, 112, 112))
        );
        bg_cafe_cakeLayout.setVerticalGroup(
            bg_cafe_cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_cafe_cake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg_chuquan.add(bg_cafe_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 870, 420));

        bg_address.setBackground(new java.awt.Color(85, 65, 118));

        text_cafeomely1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely1.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely1.setText("OMELY QUÁN  ");

        icon_cafe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N

        javax.swing.GroupLayout bg_addressLayout = new javax.swing.GroupLayout(bg_address);
        bg_address.setLayout(bg_addressLayout);
        bg_addressLayout.setHorizontalGroup(
            bg_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_addressLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(icon_cafe1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_cafeomely1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_addressLayout.setVerticalGroup(
            bg_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_cafe1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(text_cafeomely1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg_chuquan.add(bg_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, -1));

        bg.add(bg_chuquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 890, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nhanvienActionPerformed
        // TODO add your handling code here:
        QL_NV_GUI nv = new QL_NV_GUI();
        nv.setTentk(TaiKhoan);
        nv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_nhanvienActionPerformed

    private void button_thucdonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thucdonActionPerformed
        // TODO add your handling code here:
        Thuc_don_GUI td = new Thuc_don_GUI();
        td.setTentk(TaiKhoan);
        td.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_thucdonActionPerformed

    private void button_khachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_khachhangActionPerformed
        // TODO add your handling code here:
        QL_KH_GUI kh = new QL_KH_GUI();
        kh.setTentk(TaiKhoan);
        kh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_khachhangActionPerformed

    private void button_nhaphangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nhaphangActionPerformed
        // TODO add your handling code here:
        NhapHang_GUI nh = new NhapHang_GUI();
        nh.setTentk(TaiKhoan);
        nh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_nhaphangActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void button_banhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_banhangActionPerformed
        // TODO add your handling code here:
        home_banhang bh = new home_banhang();
        bh.setTaiKhoan(TaiKhoan);
        bh.setNguoigoi("Chu Quan");
        bh.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_button_banhangActionPerformed

    private void button_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dangxuatActionPerformed
        // TODO add your handling code here:
        new DangNhapGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_dangxuatActionPerformed

    private void button_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_banActionPerformed
        // TODO add your handling code here:
        Ban_GUI ban = new Ban_GUI();
        ban.setTentk(TaiKhoan);
        ban.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_banActionPerformed

    private void button_nguyenlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nguyenlieuActionPerformed
        // TODO add your handling code here:
        NguyenLieu_GUI nl = new NguyenLieu_GUI();
        nl.setTentk(TaiKhoan);
        nl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_nguyenlieuActionPerformed

    private void button_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thongkeActionPerformed
        // TODO add your handling code here:
        ThongKe_GUI tk = new ThongKe_GUI();
        tk.setNguoigoi("Chu quan");
        tk.setTentk(TaiKhoan);
        tk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_thongkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chu_Quan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chu_Quan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chu_Quan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chu_Quan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chu_Quan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg_address;
    private javax.swing.JPanel bg_ban;
    private javax.swing.JPanel bg_banhang;
    private javax.swing.JPanel bg_cafe_cake;
    private javax.swing.JPanel bg_cafeomely;
    private javax.swing.JPanel bg_chuquan;
    private javax.swing.JPanel bg_khachhang;
    private javax.swing.JPanel bg_nguyenlieu;
    private javax.swing.JPanel bg_nhaphang;
    private javax.swing.JPanel bg_nv;
    private javax.swing.JPanel bg_thoat;
    private javax.swing.JPanel bg_thongke;
    private javax.swing.JPanel bg_thucdon;
    private javax.swing.JPanel bg_trangchu;
    private javax.swing.JButton button_ban;
    private javax.swing.JButton button_banhang;
    private javax.swing.JButton button_dangxuat;
    private javax.swing.JButton button_khachhang;
    private javax.swing.JButton button_nguyenlieu;
    private javax.swing.JButton button_nhanvien;
    private javax.swing.JButton button_nhaphang;
    private javax.swing.JButton button_thongke;
    private javax.swing.JButton button_thucdon;
    private javax.swing.JLabel icon_ban;
    private javax.swing.JLabel icon_banhang;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_cafe1;
    private javax.swing.JLabel icon_khachhang;
    private javax.swing.JLabel icon_nguyenlieu;
    private javax.swing.JLabel icon_nhanvien;
    private javax.swing.JLabel icon_nhaphang;
    private javax.swing.JLabel icon_thongke;
    private javax.swing.JLabel icon_thucdon;
    private javax.swing.JLabel icon_trangchu;
    private javax.swing.JLabel image_cafe_cake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel text_cafeomely1;
    private javax.swing.JLabel text_trangchu;
    // End of variables declaration//GEN-END:variables
}
