/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

import BLL.QuanLyNV_BLL;
import DAL.DangNhapChuQuanDAL;
import DAL.DangNhapNVDAL;
import DataTranferObject.DangNhapDTO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI2
 */
public class DangNhapGUI extends javax.swing.JFrame {

    protected void XuLyDangNhap() {
        DangNhapNVDAL NV_DangNhap = new DangNhapNVDAL();
        DangNhapChuQuanDAL ChuQuan_DangNhap = new DangNhapChuQuanDAL();
        DangNhapDTO NV = NV_DangNhap.DangNhap(Text_user.getText(), Text_password.getText());
        DangNhapDTO ChuQuan = ChuQuan_DangNhap.DangNhap(Text_user.getText(), Text_password.getText());

        String tk = this.Text_user.getText();
        
        
        if (NV != null) {
            JOptionPane.showMessageDialog(null, "Đăng nhập thành công.");
            
            NV_thungan nv = new NV_thungan();
            nv.setTaiKhoan(tk);
            nv.setVisible(true);
            this.dispose();
        } else if (ChuQuan != null) {
            JOptionPane.showMessageDialog(null, "Đăng nhập thành công.");
            Chu_Quan cq = new Chu_Quan();
            cq.setTaiKhoan(tk);
            cq.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Thông tin tài khoản hoặc mật khẩu bị sai! Vui lòng nhập lại!.");
        }

    }

    /**
     * Creates new form DangNhapGUI
     */
    public DangNhapGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        text_dangnhap = new javax.swing.JLabel();
        bglogin = new javax.swing.JPanel();
        username = new javax.swing.JPanel();
        icon_account = new javax.swing.JLabel();
        Text_user = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        password = new javax.swing.JPanel();
        icon_unlock = new javax.swing.JLabel();
        Text_password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        bg_show_password = new javax.swing.JPanel();
        jCheck_show_password = new javax.swing.JCheckBox();
        button_back = new javax.swing.JButton();
        button_login = new javax.swing.JButton();
        bg_cafeomely = new javax.swing.JPanel();
        text_cafeomely = new javax.swing.JLabel();
        icon_cafe = new javax.swing.JLabel();
        bg_address = new javax.swing.JPanel();
        icon_address = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setMaximizedBounds(new java.awt.Rectangle(300, 100, 715, 845));
        setMaximumSize(new java.awt.Dimension(565, 675));
        setMinimumSize(new java.awt.Dimension(565, 675));
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(54, 33, 89));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        bg.setLayout(null);

        text_dangnhap.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        text_dangnhap.setForeground(new java.awt.Color(255, 153, 0));
        text_dangnhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_dangnhap.setText("Đăng Nhập");
        bg.add(text_dangnhap);
        text_dangnhap.setBounds(120, 100, 350, 68);

        bglogin.setOpaque(false);

        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        username.setOpaque(false);
        username.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_user_48px.png"))); // NOI18N
        username.add(icon_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 47, 40));

        Text_user.setBackground(new java.awt.Color(54, 33, 89));
        Text_user.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Text_user.setForeground(new java.awt.Color(255, 255, 255));
        Text_user.setText("Nhập tên tài khoản");
        Text_user.setBorder(null);
        Text_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_userFocusLost(evt);
            }
        });
        Text_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_userActionPerformed(evt);
            }
        });
        username.add(Text_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 273, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        username.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 280, 2));

        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        password.setOpaque(false);
        password.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_unlock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_unlock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_password_48px.png"))); // NOI18N
        password.add(icon_unlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 40, 50));

        Text_password.setBackground(new java.awt.Color(54, 33, 89));
        Text_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Text_password.setForeground(new java.awt.Color(255, 255, 255));
        Text_password.setText("12345");
        Text_password.setBorder(null);
        Text_password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Text_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_passwordFocusLost(evt);
            }
        });
        Text_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_passwordKeyPressed(evt);
            }
        });
        password.add(Text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 273, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        password.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 280, 3));

        jCheck_show_password.setBackground(new java.awt.Color(255, 255, 255));
        jCheck_show_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCheck_show_password.setText("Hiển thị mật khẩu");
        jCheck_show_password.setBorder(null);
        jCheck_show_password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheck_show_password.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheck_show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck_show_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_show_passwordLayout = new javax.swing.GroupLayout(bg_show_password);
        bg_show_password.setLayout(bg_show_passwordLayout);
        bg_show_passwordLayout.setHorizontalGroup(
            bg_show_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_show_passwordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheck_show_password, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        bg_show_passwordLayout.setVerticalGroup(
            bg_show_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheck_show_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        button_back.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_back_arrow_30px.png"))); // NOI18N
        button_back.setText("Thoát");
        button_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });

        button_login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_login_30px_1.png"))); // NOI18N
        button_login.setText("Đăng Nhập");
        button_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        bg_cafeomely.setBackground(new java.awt.Color(204, 204, 204));

        text_cafeomely.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        text_cafeomely.setText("OMELY QUÁN");

        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafeomelyLayout = new javax.swing.GroupLayout(bg_cafeomely);
        bg_cafeomely.setLayout(bg_cafeomelyLayout);
        bg_cafeomelyLayout.setHorizontalGroup(
            bg_cafeomelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_cafeomelyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_cafe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_cafeomely, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        bg_cafeomelyLayout.setVerticalGroup(
            bg_cafeomelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_cafeomely, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(icon_cafe, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        bg_address.setBackground(new java.awt.Color(204, 204, 204));

        icon_address.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_address_48px.png"))); // NOI18N

        javax.swing.GroupLayout bg_addressLayout = new javax.swing.GroupLayout(bg_address);
        bg_address.setLayout(bg_addressLayout);
        bg_addressLayout.setHorizontalGroup(
            bg_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_addressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_address)
                .addGap(466, 466, 466))
        );
        bg_addressLayout.setVerticalGroup(
            bg_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgloginLayout = new javax.swing.GroupLayout(bglogin);
        bglogin.setLayout(bgloginLayout);
        bgloginLayout.setHorizontalGroup(
            bgloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgloginLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(bgloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgloginLayout.createSequentialGroup()
                        .addComponent(bg_cafeomely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgloginLayout.createSequentialGroup()
                        .addComponent(bg_address, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgloginLayout.createSequentialGroup()
                .addGroup(bgloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgloginLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgloginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(bgloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bg_show_password, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91))
        );
        bgloginLayout.setVerticalGroup(
            bgloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgloginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg_show_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(bgloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(bg_cafeomely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        bg.add(bglogin);
        bglogin.setBounds(0, 170, 560, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_backActionPerformed

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        // TODO add your handling code here:
        if(Text_user.getText().equals("Nhập tên tài khoản") || Text_user.getText().equals("")
           || Text_password.getText().equals("12345") || Text_password.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập đầy đủ thông tin tài khoản !", "Thông báo", JOptionPane.NO_OPTION);
            return;
        }
        XuLyDangNhap();
    }//GEN-LAST:event_button_loginActionPerformed

    private void jCheck_show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck_show_passwordActionPerformed
        // TODO add your handling code here:
        if (jCheck_show_password.isSelected()) {
            Text_password.setEchoChar((char) 0);
        } else {
            Text_password.setEchoChar('*');
        }

    }//GEN-LAST:event_jCheck_show_passwordActionPerformed

    private void Text_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_userFocusLost

        //Nếu text user name = "" thì vẫn dữ mặc định màu chữ mờ và thông báo chuỗi "Nhập tên tài khoản"
        if(Text_user.getText().equals("")){
            Text_user.setText("Nhập tên tài khoản");
            Text_user.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Text_userFocusLost

    private void Text_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_userFocusGained
        
        // hàm để tạo events khi nhấn chuột vào khung tên tài khoản thay đổi màu chữ thành trắng và đồng thời cho phép nhập tên tài khoản
        if(Text_user.getText().equals("Nhập tên tài khoản")){
            Text_user.setText("");
            Text_user.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Text_userFocusGained

    private void Text_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_passwordFocusGained
        // TODO add your handling code here:
        
        if(Text_password.getText().equals("12345")){
            Text_password.setText("");
            Text_password.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Text_passwordFocusGained

    private void Text_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_passwordFocusLost
        //Nếu text user name = '' thì vẫn dữ mặc định màu chữ mờ
        if(Text_password.getText().equals("")){
            Text_password.setText("12345");
            Text_password.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Text_passwordFocusLost

    private void Text_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_passwordKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            XuLyDangNhap();
            return;
        }
    }//GEN-LAST:event_Text_passwordKeyPressed

    private void Text_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Text_password;
    private javax.swing.JTextField Text_user;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg_address;
    private javax.swing.JPanel bg_cafeomely;
    private javax.swing.JPanel bg_show_password;
    private javax.swing.JPanel bglogin;
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel icon_account;
    private javax.swing.JLabel icon_address;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_unlock;
    private javax.swing.JCheckBox jCheck_show_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel password;
    private javax.swing.JLabel text_cafeomely;
    private javax.swing.JLabel text_dangnhap;
    private javax.swing.JPanel username;
    // End of variables declaration//GEN-END:variables
}
