/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

/**
 *
 * @author MSI2
 */
public class home_banhang extends javax.swing.JFrame {

    private String TaiKhoan;
    private String nguoigoi;

    public String getNguoigoi() {
        return nguoigoi;
    }

    public void setNguoigoi(String nguoigoi) {
        this.nguoigoi = nguoigoi;
    }
    
    public String getTaiKhoan() {
        return TaiKhoan;
    }

    public void setTaiKhoan(String TaiKhoan) {
        this.TaiKhoan = TaiKhoan;
    }

    
    public home_banhang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgnv = new javax.swing.JPanel();
        sidepane7 = new javax.swing.JPanel();
        bg_banhang = new javax.swing.JPanel();
        icon_banhang = new javax.swing.JLabel();
        button_themhd = new javax.swing.JButton();
        bg_thucdon = new javax.swing.JPanel();
        icon_thucdon = new javax.swing.JLabel();
        button_tracuuhd = new javax.swing.JButton();
        bg_thoat = new javax.swing.JPanel();
        text_trangchu7 = new javax.swing.JLabel();
        icon_trangchu7 = new javax.swing.JLabel();
        button_thoat = new javax.swing.JButton();
        bg_chuquan = new javax.swing.JPanel();
        bg_cafeomely = new javax.swing.JPanel();
        icon_cafe = new javax.swing.JLabel();
        bg_cafe_cake = new javax.swing.JPanel();
        image_cafe_cake = new javax.swing.JLabel();
        bg_address = new javax.swing.JPanel();
        text_cafeomely1 = new javax.swing.JLabel();
        icon_cafe1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgnv.setBackground(new java.awt.Color(255, 255, 255));
        bgnv.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bgnv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane7.setBackground(new java.awt.Color(54, 33, 89));
        sidepane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_banhang.setBackground(new java.awt.Color(85, 65, 118));

        icon_banhang.setBackground(new java.awt.Color(54, 33, 89));
        icon_banhang.setForeground(new java.awt.Color(255, 255, 255));
        icon_banhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_banhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/banhang/icons8_add_new_26px.png"))); // NOI18N
        icon_banhang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_banhang.setOpaque(true);

        button_themhd.setBackground(new java.awt.Color(54, 33, 89));
        button_themhd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_themhd.setForeground(new java.awt.Color(255, 255, 255));
        button_themhd.setText("Thêm hóa đơn");
        button_themhd.setOpaque(false);
        button_themhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_themhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_banhangLayout = new javax.swing.GroupLayout(bg_banhang);
        bg_banhang.setLayout(bg_banhangLayout);
        bg_banhangLayout.setHorizontalGroup(
            bg_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_banhangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(icon_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_themhd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_banhangLayout.setVerticalGroup(
            bg_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_themhd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_banhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane7.add(bg_banhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 40));

        bg_thucdon.setBackground(new java.awt.Color(85, 65, 118));

        icon_thucdon.setBackground(new java.awt.Color(54, 33, 89));
        icon_thucdon.setForeground(new java.awt.Color(255, 255, 255));
        icon_thucdon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_thucdon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/banhang/icons8_search_26px.png"))); // NOI18N
        icon_thucdon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_thucdon.setOpaque(true);

        button_tracuuhd.setBackground(new java.awt.Color(54, 33, 89));
        button_tracuuhd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_tracuuhd.setForeground(new java.awt.Color(255, 255, 255));
        button_tracuuhd.setText("Tra cứu hóa đơn");
        button_tracuuhd.setActionCommand("Thực dơn");
        button_tracuuhd.setOpaque(false);
        button_tracuuhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tracuuhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thucdonLayout = new javax.swing.GroupLayout(bg_thucdon);
        bg_thucdon.setLayout(bg_thucdonLayout);
        bg_thucdonLayout.setHorizontalGroup(
            bg_thucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_thucdonLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(icon_thucdon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_tracuuhd, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bg_thucdonLayout.setVerticalGroup(
            bg_thucdonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_tracuuhd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_thucdon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane7.add(bg_thucdon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 310, 40));

        bgnv.add(sidepane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 560));

        bg_thoat.setBackground(new java.awt.Color(85, 65, 118));
        bg_thoat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_trangchu7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu7.setText("Bán hàng");
        bg_thoat.add(text_trangchu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 13, 239, 34));

        icon_trangchu7.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_online_store_32px.png"))); // NOI18N
        icon_trangchu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu7.setOpaque(true);
        bg_thoat.add(icon_trangchu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 65, 60));

        button_thoat.setBackground(new java.awt.Color(255, 255, 255));
        button_thoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat.setForeground(new java.awt.Color(204, 51, 0));
        button_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_back_arrow_30px.png"))); // NOI18N
        button_thoat.setText("Thoát");
        button_thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });
        bg_thoat.add(button_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 15, 110, -1));

        bgnv.add(bg_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        bg_chuquan.setBackground(new java.awt.Color(54, 33, 89));
        bg_chuquan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_cafeomely.setBackground(new java.awt.Color(85, 65, 118));

        icon_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafeomelyLayout = new javax.swing.GroupLayout(bg_cafeomely);
        bg_cafeomely.setLayout(bg_cafeomelyLayout);
        bg_cafeomelyLayout.setHorizontalGroup(
            bg_cafeomelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_cafeomelyLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(icon_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(671, 671, 671))
        );
        bg_cafeomelyLayout.setVerticalGroup(
            bg_cafeomelyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_cafe, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg_chuquan.add(bg_cafeomely, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 870, -1));

        bg_cafe_cake.setBackground(new java.awt.Color(54, 33, 89));

        image_cafe_cake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_cafe_cake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/quan_cafe.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafe_cakeLayout = new javax.swing.GroupLayout(bg_cafe_cake);
        bg_cafe_cake.setLayout(bg_cafe_cakeLayout);
        bg_cafe_cakeLayout.setHorizontalGroup(
            bg_cafe_cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_cafe_cakeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(image_cafe_cake, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        bg_cafe_cakeLayout.setVerticalGroup(
            bg_cafe_cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_cafe_cake, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg_chuquan.add(bg_cafe_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 880, 420));

        bg_address.setBackground(new java.awt.Color(85, 65, 118));

        text_cafeomely1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely1.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely1.setText("OMELY QUÁN ");

        icon_cafe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N

        javax.swing.GroupLayout bg_addressLayout = new javax.swing.GroupLayout(bg_address);
        bg_address.setLayout(bg_addressLayout);
        bg_addressLayout.setHorizontalGroup(
            bg_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_addressLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(icon_cafe1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_cafeomely1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_addressLayout.setVerticalGroup(
            bg_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_cafe1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(text_cafeomely1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg_chuquan.add(bg_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, -1));

        bgnv.add(bg_chuquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 890, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgnv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_tracuuhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tracuuhdActionPerformed
        // TODO add your handling code here:
        if(nguoigoi.equals("Chu Quan"))
        {
            tra_cuu_hd tim_hd = new tra_cuu_hd();
            tim_hd.setTaiKhoan(TaiKhoan);
            tim_hd.setVisible(true);
            this.dispose();
            return;
        }
        if(nguoigoi.equals("Nhan Vien"))
        {
            TraCuuHD_NV_GUI tim_hd = new TraCuuHD_NV_GUI();
            tim_hd.setTaiKhoan(TaiKhoan);
            tim_hd.setVisible(true);
            this.dispose();
            return;
        
        }
    }//GEN-LAST:event_button_tracuuhdActionPerformed

    private void button_themhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_themhdActionPerformed
        // TODO add your handling code here:
        if(nguoigoi.equals("Chu Quan"))
        {
            tao_hd new_hd = new tao_hd();
            new_hd.setTaiKhoan(TaiKhoan);
            new_hd.setVisible(true);
            this.dispose();
            return;
        }
        if(nguoigoi.equals("Nhan Vien"))
        {
            TaoHD_NV_GUI new_hd = new TaoHD_NV_GUI();
            new_hd.setTaiKhoan(TaiKhoan);
            new_hd.setVisible(true);
            this.dispose();
            return;
        
        }
    }//GEN-LAST:event_button_themhdActionPerformed

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thoatActionPerformed
        // TODO add your handling code here:
        if(nguoigoi.equals("Chu Quan"))
        {
            Chu_Quan cq = new Chu_Quan();
            cq.setTaiKhoan(TaiKhoan);
            cq.setVisible(true);
            this.dispose();
            return;
        }
        else
        {
            NV_thungan nv = new NV_thungan();
            nv.setTaiKhoan(TaiKhoan);
            nv.setVisible(true);
            this.dispose();
            return;
        }

    }//GEN-LAST:event_button_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_banhang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_banhang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_address;
    private javax.swing.JPanel bg_banhang;
    private javax.swing.JPanel bg_cafe_cake;
    private javax.swing.JPanel bg_cafeomely;
    private javax.swing.JPanel bg_chuquan;
    private javax.swing.JPanel bg_thoat;
    private javax.swing.JPanel bg_thucdon;
    private javax.swing.JPanel bgnv;
    private javax.swing.JButton button_themhd;
    private javax.swing.JButton button_thoat;
    private javax.swing.JButton button_tracuuhd;
    private javax.swing.JLabel icon_banhang;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_cafe1;
    private javax.swing.JLabel icon_thucdon;
    private javax.swing.JLabel icon_trangchu7;
    private javax.swing.JLabel image_cafe_cake;
    private javax.swing.JPanel sidepane7;
    private javax.swing.JLabel text_cafeomely1;
    private javax.swing.JLabel text_trangchu7;
    // End of variables declaration//GEN-END:variables
}
