/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

import BLL.QuanLyNV_BLL;
import DAL.NhanVienDAL;
import DTO.NhanVienDTO;
import DTO.TaiKhoanDTO;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI2
 */
public class QL_NV_GUI extends javax.swing.JFrame {
    private String tentk;

    public String getTentk() {
        return tentk;
    }

    public void setTentk(String tentk) {
        this.tentk = tentk;
    }
    

    /**
     * Creates new form QL_NV_GUI
     */
    public QL_NV_GUI() {
        initComponents();
        setDefaultNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgnv = new javax.swing.JPanel();
        bg_thoat = new javax.swing.JPanel();
        text_trangchu7 = new javax.swing.JLabel();
        icon_trangchu7 = new javax.swing.JLabel();
        button_thoat = new javax.swing.JButton();
        bg_chuquan = new javax.swing.JPanel();
        bg_cafeomely = new javax.swing.JPanel();
        icon_cafe = new javax.swing.JLabel();
        icon_cafe1 = new javax.swing.JLabel();
        text_cafeomely1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbo_loaitk = new javax.swing.JComboBox<>();
        txtTennv = new javax.swing.JTextField();
        txtCmnd = new javax.swing.JTextField();
        txtDc = new javax.swing.JTextField();
        txtMk = new javax.swing.JTextField();
        txtNvl = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtMucluong = new javax.swing.JTextField();
        txtTentk = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboGt = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txt_nsinh = new javax.swing.JTextField();
        btn_huy = new javax.swing.JButton();
        btn_dy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ttNV = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        bt_refresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        bt_themNV = new javax.swing.JButton();
        bt_xoaNV = new javax.swing.JButton();
        bt_suaNV = new javax.swing.JButton();
        bt_timNV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgnv.setBackground(new java.awt.Color(255, 255, 255));
        bgnv.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bgnv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_thoat.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu7.setText("Quản lý nhân viên");

        icon_trangchu7.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_management_24px.png"))); // NOI18N
        icon_trangchu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu7.setOpaque(true);

        button_thoat.setBackground(new java.awt.Color(255, 255, 255));
        button_thoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat.setForeground(new java.awt.Color(204, 51, 0));
        button_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_back_arrow_30px.png"))); // NOI18N
        button_thoat.setText("Thoát");
        button_thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thoatLayout = new javax.swing.GroupLayout(bg_thoat);
        bg_thoat.setLayout(bg_thoatLayout);
        bg_thoatLayout.setHorizontalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(icon_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 756, Short.MAX_VALUE)
                .addComponent(button_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_thoatLayout.setVerticalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(button_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(icon_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bgnv.add(bg_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        bg_chuquan.setBackground(new java.awt.Color(54, 33, 89));
        bg_chuquan.setToolTipText("");
        bg_chuquan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_cafeomely.setBackground(new java.awt.Color(85, 65, 118));
        bg_cafeomely.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N
        bg_cafeomely.add(icon_cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 79, 56));

        icon_cafe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N
        bg_cafeomely.add(icon_cafe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 79, 56));

        text_cafeomely1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely1.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely1.setText("OMELY QUÁN ");
        bg_cafeomely.add(text_cafeomely1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 275, 56));

        bg_chuquan.add(bg_cafeomely, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 506, 1180, 50));

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên Nhân Viên");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 89, 21));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số CMND");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 89, 21));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 89, 21));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Địa chỉ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 89, 21));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SĐT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 89, 21));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ngày vào làm");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, 21));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("VNĐ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mức lương");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 89, 21));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Loại tài khoản");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 89, 21));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mật khẩu");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 89, 21));

        cbo_loaitk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Chủ quán" }));
        cbo_loaitk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_loaitkActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_loaitk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 120, 30));

        txtTennv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtTennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 30));

        txtCmnd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 140, 30));

        txtDc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDcActionPerformed(evt);
            }
        });
        jPanel1.add(txtDc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 30));

        txtMk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtMk, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, 30));

        txtNvl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNvl.setForeground(new java.awt.Color(204, 204, 204));
        txtNvl.setText("dd-mm-yyyy");
        txtNvl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNvlFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNvlFocusLost(evt);
            }
        });
        txtNvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNvlActionPerformed(evt);
            }
        });
        jPanel1.add(txtNvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, 30));

        txtSdt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        txtMucluong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtMucluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 30));

        txtTentk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txtTentk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tên tài khoản");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 89, 21));

        cboGt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cboGt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGtActionPerformed(evt);
            }
        });
        jPanel1.add(cboGt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ngày Sinh");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, 21));

        txt_nsinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_nsinh.setForeground(new java.awt.Color(204, 204, 204));
        txt_nsinh.setText("dd-mm-yyyy");
        txt_nsinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nsinhFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nsinhFocusLost(evt);
            }
        });
        txt_nsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nsinhActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nsinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, 30));

        btn_huy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_cancel_24px.png"))); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_huy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, 40));

        btn_dy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_dy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/dong y.png"))); // NOI18N
        btn_dy.setText("Đồng ý");
        btn_dy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));
        btn_dy.setEnabled(false);
        btn_dy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, 40));

        bg_chuquan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 490));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_ttNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên tài khoản", "Họ và tên", "CMND", "Ngày sinh", "Địa chỉ", "Giởi tính", "SĐT", "NGVL", "Mức lương"
            }
        ));
        jScrollPane1.setViewportView(tb_ttNV);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 820, 340));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Thông tin nhân viên");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 270, 30));

        bt_refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_refresh_16px.png"))); // NOI18N
        bt_refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 97, 97), 2));
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });
        jPanel2.add(bt_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 50, 40));

        bg_chuquan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 840, 390));

        jPanel4.setBackground(new java.awt.Color(85, 65, 118));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Chức năng");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 97, 97), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 97, 97), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 97, 97), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_themNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_themNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_add_30px.png"))); // NOI18N
        bt_themNV.setText("Thêm");
        bt_themNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));
        bt_themNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themNVActionPerformed(evt);
            }
        });

        bt_xoaNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_xoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/delete.png"))); // NOI18N
        bt_xoaNV.setText("Xóa");
        bt_xoaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));
        bt_xoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaNVActionPerformed(evt);
            }
        });

        bt_suaNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_suaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/sửa .png"))); // NOI18N
        bt_suaNV.setText("Cập nhật");
        bt_suaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));
        bt_suaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suaNVActionPerformed(evt);
            }
        });

        bt_timNV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_timNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_google_web_search_50px.png"))); // NOI18N
        bt_timNV.setText("Tra cứu");
        bt_timNV.setAlignmentY(0.0F);
        bt_timNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        bt_timNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bt_themNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_timNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_xoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(bt_suaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt_timNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_themNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_xoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_suaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(40, 40, 40))
        );

        bg_chuquan.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 620, 80));

        bgnv.add(bg_chuquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1200, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgnv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        // TODO add your handling code here:
        this.setDefaultNhanVien();
        
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thoatActionPerformed
        // TODO add your handling code here:
        Chu_Quan cq = new Chu_Quan();
        cq.setTaiKhoan(tentk);
        cq.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_thoatActionPerformed

    private void txtDcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDcActionPerformed

    private void cbo_loaitkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_loaitkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_loaitkActionPerformed

    private void bt_themNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themNVActionPerformed
        if(btn_dy.isEnabled())
        {
            JOptionPane.showMessageDialog(rootPane, "Nhân viên này đã tồn tại !", "Thông báo", JOptionPane.NO_OPTION);
            return;
        }
        QuanLyNV_BLL ql_nv = new QuanLyNV_BLL();
        String Ten_nv = txtTennv.getText();
        String cmnd = txtCmnd.getText();
        String ngaysinh = txt_nsinh.getText();
          
        String diachi = txtDc.getText();
        String gioitinh = "";
        String sdt = txtSdt.getText();
        String mucluong = txtMucluong.getText();
        String nvl = txtNvl.getText();
        
        String tentk = txtTentk.getText();
        String mk = txtMk.getText();
        String role = "";
        
        if (cboGt.getSelectedItem().equals("Nam"))
            gioitinh = "Nam";
        else gioitinh = "Nữ";
        
        if (cbo_loaitk.getSelectedItem().equals("Nhân viên"))
            role = "0";
        else role = "1";       
        
        if(Ten_nv.equals("") || cmnd.equals("") || diachi.equals("") || ngaysinh.equals("dd-MM-yyyy") 
           || sdt.equals("") || mucluong.equals("") || nvl.equals("dd-MM-yyyy") 
           || tentk.equals("") || mk.equals(""))   
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin của nhân viên !", "Thông báo", JOptionPane.NO_OPTION);
            return;
        }
        else 
        {
            boolean kq = ql_nv.ThemNV(new NhanVienDTO(tentk, Ten_nv, cmnd, ngaysinh, diachi, gioitinh, sdt, mucluong, nvl), new TaiKhoanDTO(tentk, mk,role));
            if (kq == true)
            {   
                JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên mới thành công !", "Thông báo", JOptionPane.NO_OPTION);
                this.setDefaultNhanVien();
                return;
            } 
            else 
            {
                JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên mới thất bại !", "Thông báo", JOptionPane.NO_OPTION);
                return;
            }
        } 
    }//GEN-LAST:event_bt_themNVActionPerformed

    private void txt_nsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nsinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nsinhActionPerformed

    private void txt_nsinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nsinhFocusLost
        // TODO add your handling code here:
        if(txt_nsinh.getText().equals(""))
        {
            txt_nsinh.setText("dd-mm-yyyy");
            txt_nsinh.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txt_nsinhFocusLost

    private void txt_nsinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nsinhFocusGained
        // TODO add your handling code here:
        if(txt_nsinh.getText().equals("dd-mm-yyyy"))
        {
            txt_nsinh.setText("");
            txt_nsinh.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_nsinhFocusGained

    private void txtNvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNvlActionPerformed

    private void txtNvlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNvlFocusGained
        // TODO add your handling code here:
        if(txtNvl.getText().equals("dd-mm-yyyy"))
        {
            txtNvl.setText("");
            txtNvl.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtNvlFocusGained

    private void txtNvlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNvlFocusLost
        // TODO add your handling code here:
        if(txtNvl.getText().equals(""))
        {
            txtNvl.setText("dd-mm-yyyy");
            txtNvl.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtNvlFocusLost

    private void bt_timNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timNVActionPerformed
        // TODO add your handling code here:
        Form_tracuu tc = new Form_tracuu();
        tc.setStr("Tim nhan vien");
        tc.setTentk(tentk);
        tc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_timNVActionPerformed

    private void bt_xoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaNVActionPerformed
        // TODO add your handling code here:
        int choose = this.tb_ttNV.getSelectedRow();
        if(choose < 0){
            
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một nhân viên trước khi muốn xóa !", "Thông báo", JOptionPane.NO_OPTION);
            return;
        }
        else{
            if(JOptionPane.showConfirmDialog(rootPane, "Bạn có thực sự muốn xóa nhân viên này !", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                QuanLyNV_BLL ql = new QuanLyNV_BLL();
                String manv = tb_ttNV.getModel().getValueAt(choose, 0).toString();
//                System.out.println(manv);
                String tentk = tb_ttNV.getModel().getValueAt(choose, 1).toString();
                boolean kq = ql.XoaNV(manv, tentk);
                if(kq == true)
                {
                    JOptionPane.showMessageDialog(rootPane, "Nhân viên đã được xóa bỏ !", "Thông báo", JOptionPane.NO_OPTION);
                    this.setDefaultNhanVien();
                    return;
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Xóa nhân viên không thành công !", "Thông báo", JOptionPane.NO_OPTION);
                    return;
                }
                
            }
            return;
        }
    }//GEN-LAST:event_bt_xoaNVActionPerformed

    private void bt_suaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suaNVActionPerformed
        // TODO add your handling code here:
        int choose = this.tb_ttNV.getSelectedRow();
        if(choose < 0){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 nhân viên có trong danh sách để cập nhật thông tin !", "Thông báo", JOptionPane.NO_OPTION);
            return;
        }
        else{
            QuanLyNV_BLL ql = new QuanLyNV_BLL();
            NhanVienDTO nv = ql.getNhanVien(tb_ttNV.getModel().getValueAt(choose, 0).toString());
            
            String tentk = nv.getTenTK();
            this.txtTentk.setText(tentk);  
            this.txtTentk.setEnabled(false);
            
            String tennv = nv.getHoTen();
            this.txtTennv.setText(tennv); 
            
            String cmnd = nv.getCMND();
            this.txtCmnd.setText(cmnd); 
            
            String ngsinh = nv.getNgaysinh();
            this.txt_nsinh.setForeground(Color.BLACK);
            this.txt_nsinh.setText(ngsinh); 
            
            String diachi = nv.getDiaChi();
            this.txtDc.setText(diachi);
            
            String gt = nv.getGioiTinh();
            if(gt.equals("Nam"))
                this.cboGt.setSelectedIndex(0);
            else this.cboGt.setSelectedIndex(1);
            this.cboGt.setEnabled(false);
            
            String sdt = nv.getSDT();
            this.txtSdt.setText(sdt); 
            
            String nvl = nv.getNVL();
            this.txtNvl.setForeground(Color.BLACK);
            this.txtNvl.setText(nvl); 
            
            String luong = nv.getMucLuong();
            this.txtMucluong.setText(luong);  
            
            TaiKhoanDTO tk = ql.getTaiKhoan(txtTentk.getText());
            
            String mk = tk.getMK();
            this.txtMk.setText(mk);
            
            String loaitk = tk.getRole();
            if(loaitk.equalsIgnoreCase("1"))
                this.cbo_loaitk.setSelectedIndex(1);
            else this.cbo_loaitk.setSelectedIndex(0);
            this.cbo_loaitk.setEnabled(false); 
            this.btn_dy.setEnabled(true);
            return;
        }
            
        
    }//GEN-LAST:event_bt_suaNVActionPerformed

    
    private void cboGtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGtActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        this.txtTennv.setText(null);
        this.txtCmnd.setText(null);
        this.txtSdt.setText(null);
        this.txtDc.setText(null);
        this.cboGt.setSelectedIndex(0);
        this.cbo_loaitk.setSelectedIndex(0);
        this.txtNvl.setText(null);
        this.txt_nsinh.setText(null);
        this.txtTentk.setText(null);
        this.txtMucluong.setText(null);
        this.txtMk.setText(null);
        btn_dy.setEnabled(false);
        return;
        
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_dyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dyActionPerformed
        // TODO add your handling code here:
        QuanLyNV_BLL ql = new QuanLyNV_BLL();
        NhanVienDTO nv = ql.getNhanVien_TK(this.txtTentk.getText());
        TaiKhoanDTO tk_nv = ql.getTaiKhoan(this.txtTentk.getText());
        
        nv.setHoTen(this.txtTennv.getText());
        nv.setCMND(this.txtCmnd.getText());
        nv.setDiaChi(this.txtDc.getText());
        nv.setNgaysinh(this.txt_nsinh.getText());
        nv.setSDT(this.txtSdt.getText());
        nv.setNVL(this.txtNvl.getText());
        nv.setMucLuong(this.txtMucluong.getText());
        
        tk_nv.setMK(this.txtMk.getText());
        
        boolean kq = ql.CapNhatNV(nv, tk_nv);
        if(kq == true)
        {
            JOptionPane.showMessageDialog(rootPane, "Bạn vừa cập nhật thông tin 1 nhân viên thành công !", "Thông báo", JOptionPane.NO_OPTION);
            this.txtTennv.setText(null);
            this.txtCmnd.setText(null);
            this.txtSdt.setText(null);
            this.txtDc.setText(null);
            this.cboGt.setSelectedIndex(0);
            this.cboGt.setEnabled(true);
            this.cbo_loaitk.setSelectedIndex(0);
            this.cbo_loaitk.setEnabled(true);
            this.txtNvl.setText(null);
            this.txt_nsinh.setText(null);
            this.txtTentk.setText(null);
            this.txtTentk.setEnabled(true);
            this.txtMucluong.setText(null);
            this.txtMk.setText(null);
            this.btn_dy.setEnabled(false);
            this.setDefaultNhanVien();
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin nhân viên thất bại !", "Thông báo", JOptionPane.NO_OPTION);
            return;
        }
    }//GEN-LAST:event_btn_dyActionPerformed

    public void setDefaultNhanVien()
    {
        QuanLyNV_BLL ql = new QuanLyNV_BLL();
        DefaultTableModel model = new DefaultTableModel();
        String[] title = {"Mã nhân viên", "Tên TK", "Họ tên", "Số cmnd", "Ngày sinh", "Địa chỉ", "Giới tính", "SĐT", "Mức lương", "Ngày vào làm"};
        model.setColumnIdentifiers(title);
        ArrayList<NhanVienDTO> ar = ql.getAllNhanVien();
        for(int i=0;i < ar.size();i++)
        {
            NhanVienDTO nv = ar.get(i);
            String Manv = nv.getMaNV();
            String Ten_nv = nv.getHoTen();
            String cmnd = nv.getCMND();
            String ngaysinh = nv.getNgaysinh();
            String diachi = nv.getDiaChi();
            String gioitinh = nv.getGioiTinh();
            String sdt = nv.getSDT();
            String mucluong = nv.getMucLuong();
            String nvl = nv.getNVL();

            String tentk = nv.getTenTK();
            
            Object[]temp={Manv, tentk, Ten_nv, cmnd, diachi, ngaysinh, gioitinh,sdt, mucluong, nvl};
            model.addRow(temp);
        }
        this.tb_ttNV.setModel(model);
    }
    
    public void setTable_tracuu(NhanVienDTO nv)
    {
        DefaultTableModel model = new DefaultTableModel();
        String[] title = {"Mã nhân viên", "Tên TK", "Họ tên", "Số cmnd", "Ngày sinh", "Địa chỉ", "Giới tính", "SĐT", "Mức lương", "Ngày vào làm"};
        model.setColumnIdentifiers(title);
        String Manv = nv.getMaNV();
        String hoten = nv.getHoTen();
        String cmnd = nv.getCMND();
        String ngaysinh = nv.getNgaysinh();
        String diachi = nv.getDiaChi();
        String gioitinh = nv.getGioiTinh();
        String sdt = nv.getSDT();
        String mucluong = nv.getMucLuong();
        String nvl = nv.getNVL();

        String tentk = nv.getTenTK();
        Object[]temp={Manv, tentk, hoten, cmnd, ngaysinh, diachi, gioitinh, sdt, mucluong, nvl};
        model.addRow(temp);
        this.tb_ttNV.setModel(model);
        Object value = model.getValueAt(0,0);
        if (value ==null)
        {
                JOptionPane.showMessageDialog(null, "Không có kết quả cần tìm!");
                return;
        }
        return;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_NV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_NV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_NV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_NV_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        QL_NV_GUI f = new QL_NV_GUI();
        f.setVisible(true);
        f.setLocationRelativeTo(null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_cafeomely;
    private javax.swing.JPanel bg_chuquan;
    private javax.swing.JPanel bg_thoat;
    private javax.swing.JPanel bgnv;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_suaNV;
    private javax.swing.JButton bt_themNV;
    private javax.swing.JButton bt_timNV;
    private javax.swing.JButton bt_xoaNV;
    private javax.swing.JButton btn_dy;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton button_thoat;
    private javax.swing.JComboBox<String> cboGt;
    private javax.swing.JComboBox<String> cbo_loaitk;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_cafe1;
    private javax.swing.JLabel icon_trangchu7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ttNV;
    private javax.swing.JLabel text_cafeomely1;
    private javax.swing.JLabel text_trangchu7;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtDc;
    private javax.swing.JTextField txtMk;
    private javax.swing.JTextField txtMucluong;
    private javax.swing.JTextField txtNvl;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTennv;
    private javax.swing.JTextField txtTentk;
    private javax.swing.JTextField txt_nsinh;
    // End of variables declaration//GEN-END:variables
}
