/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

import BLL.QuanLyBH_BLL;
import BLL.QuanLyNV_BLL;
import DAL.Database;
import DAL.NhanVienDAL;
import DTO.CTHD_DTO;
import DTO.HoaDonDTO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MSI2
 */
public class tao_hd extends javax.swing.JFrame {
    private String TaiKhoan;
    public  String MaHD = null;

    public String getTaiKhoan() {
        return TaiKhoan;
    }

    public void setTaiKhoan(String TaiKhoan) {
        this.TaiKhoan = TaiKhoan;
    }
    
    
    public tao_hd() {
        initComponents();
        setComBoBox();
        
    }
    
    /**
     *
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_tracu = new javax.swing.JFrame();
        bg_tracuuhd = new javax.swing.JPanel();
        sidepane9 = new javax.swing.JPanel();
        bg_trangchu9 = new javax.swing.JPanel();
        text_trangchu9 = new javax.swing.JLabel();
        icon_trangchu9 = new javax.swing.JLabel();
        bg_banhang2 = new javax.swing.JPanel();
        icon_banhang2 = new javax.swing.JLabel();
        button_banhang2 = new javax.swing.JButton();
        bg_thucdon2 = new javax.swing.JPanel();
        icon_thucdon2 = new javax.swing.JLabel();
        button_thucdon2 = new javax.swing.JButton();
        bg_address2 = new javax.swing.JPanel();
        text_cafeomely4 = new javax.swing.JLabel();
        icon_cafe4 = new javax.swing.JLabel();
        bg_thoat2 = new javax.swing.JPanel();
        button_thoat2 = new javax.swing.JButton();
        bg_chuquan2 = new javax.swing.JPanel();
        bg_cafeomely2 = new javax.swing.JPanel();
        text_cafeomely5 = new javax.swing.JLabel();
        icon_cafe5 = new javax.swing.JLabel();
        bg_cafe_cake2 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        bg7 = new javax.swing.JPanel();
        bg_thoat = new javax.swing.JPanel();
        bg_trangchu7 = new javax.swing.JPanel();
        text_trangchu7 = new javax.swing.JLabel();
        icon_trangchu7 = new javax.swing.JLabel();
        button_thoat = new javax.swing.JButton();
        bg_home_banhang = new javax.swing.JPanel();
        them_hd = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        sp_sl = new javax.swing.JSpinner();
        txf_tongcong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        tx_giamgia = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        tx_gia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        bt_them = new javax.swing.JButton();
        cb_maban = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_CTHD = new javax.swing.JTable();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        themhd = new javax.swing.JPanel();
        icon_themhd = new javax.swing.JLabel();
        bt_themhd = new javax.swing.JButton();
        bt_thanhtoan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bt_Xuathd = new javax.swing.JButton();
        bt_bochon = new javax.swing.JButton();
        cb_makh = new javax.swing.JComboBox<>();
        cb_tenmon = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tx_thanhtoan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bg_address = new javax.swing.JPanel();
        text_cafeomely1 = new javax.swing.JLabel();
        icon_cafe1 = new javax.swing.JLabel();
        icon_cafe = new javax.swing.JLabel();

        bg_tracuuhd.setBackground(new java.awt.Color(255, 255, 255));
        bg_tracuuhd.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bg_tracuuhd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane9.setBackground(new java.awt.Color(54, 33, 89));
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_trangchu9.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu9.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu9.setText("Bán Hàng");

        icon_trangchu9.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu9.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_online_store_32px.png"))); // NOI18N
        icon_trangchu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu9.setOpaque(true);

        javax.swing.GroupLayout bg_trangchu9Layout = new javax.swing.GroupLayout(bg_trangchu9);
        bg_trangchu9.setLayout(bg_trangchu9Layout);
        bg_trangchu9Layout.setHorizontalGroup(
            bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_trangchu9Layout.createSequentialGroup()
                .addComponent(icon_trangchu9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
            .addGroup(bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_trangchu9Layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(text_trangchu9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        bg_trangchu9Layout.setVerticalGroup(
            bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_trangchu9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(bg_trangchu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(text_trangchu9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        sidepane9.add(bg_trangchu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        bg_banhang2.setBackground(new java.awt.Color(85, 65, 118));

        icon_banhang2.setBackground(new java.awt.Color(54, 33, 89));
        icon_banhang2.setForeground(new java.awt.Color(255, 255, 255));
        icon_banhang2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_banhang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_shop_26px.png"))); // NOI18N
        icon_banhang2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_banhang2.setOpaque(true);

        button_banhang2.setBackground(new java.awt.Color(54, 33, 89));
        button_banhang2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_banhang2.setForeground(new java.awt.Color(255, 255, 255));
        button_banhang2.setText("Thêm hóa đơn mới");
        button_banhang2.setOpaque(false);
        button_banhang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_banhang2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_banhang2Layout = new javax.swing.GroupLayout(bg_banhang2);
        bg_banhang2.setLayout(bg_banhang2Layout);
        bg_banhang2Layout.setHorizontalGroup(
            bg_banhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_banhang2Layout.createSequentialGroup()
                .addComponent(icon_banhang2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_banhang2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        bg_banhang2Layout.setVerticalGroup(
            bg_banhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_banhang2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_banhang2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane9.add(bg_banhang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 310, 40));

        bg_thucdon2.setBackground(new java.awt.Color(85, 65, 118));

        icon_thucdon2.setBackground(new java.awt.Color(54, 33, 89));
        icon_thucdon2.setForeground(new java.awt.Color(255, 255, 255));
        icon_thucdon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_thucdon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_cutlery_26px.png"))); // NOI18N
        icon_thucdon2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_thucdon2.setOpaque(true);

        button_thucdon2.setBackground(new java.awt.Color(54, 33, 89));
        button_thucdon2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thucdon2.setForeground(new java.awt.Color(255, 255, 255));
        button_thucdon2.setText("Tra cứu hóa đơn");
        button_thucdon2.setActionCommand("Thực dơn");
        button_thucdon2.setOpaque(false);
        button_thucdon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thucdon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thucdon2Layout = new javax.swing.GroupLayout(bg_thucdon2);
        bg_thucdon2.setLayout(bg_thucdon2Layout);
        bg_thucdon2Layout.setHorizontalGroup(
            bg_thucdon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_thucdon2Layout.createSequentialGroup()
                .addComponent(icon_thucdon2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_thucdon2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        bg_thucdon2Layout.setVerticalGroup(
            bg_thucdon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_thucdon2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_thucdon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane9.add(bg_thucdon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, 40));

        bg_address2.setBackground(new java.awt.Color(85, 65, 118));
        bg_address2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_cafeomely4.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely4.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely4.setText("OMELY QUÁN");
        bg_address2.add(text_cafeomely4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 0, 235, 56));

        icon_cafe4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N
        bg_address2.add(icon_cafe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        sidepane9.add(bg_address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 310, 50));

        bg_tracuuhd.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 620));

        bg_thoat2.setBackground(new java.awt.Color(85, 65, 118));

        button_thoat2.setBackground(new java.awt.Color(255, 51, 0));
        button_thoat2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat2.setForeground(new java.awt.Color(255, 255, 255));
        button_thoat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_back_32px.png"))); // NOI18N
        button_thoat2.setText("Thoát");
        button_thoat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        button_thoat2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout bg_thoat2Layout = new javax.swing.GroupLayout(bg_thoat2);
        bg_thoat2.setLayout(bg_thoat2Layout);
        bg_thoat2Layout.setHorizontalGroup(
            bg_thoat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoat2Layout.createSequentialGroup()
                .addContainerGap(580, Short.MAX_VALUE)
                .addComponent(button_thoat2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_thoat2Layout.setVerticalGroup(
            bg_thoat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_thoat2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg_tracuuhd.add(bg_thoat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 690, 60));

        bg_chuquan2.setBackground(new java.awt.Color(54, 33, 89));
        bg_chuquan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_cafeomely2.setBackground(new java.awt.Color(85, 65, 118));

        text_cafeomely5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_cafeomely5.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely5.setText("Đ/C: Thị trấn Phú Phong, huyện Tây Sơn, tỉnh Bình Định.");

        icon_cafe5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N

        javax.swing.GroupLayout bg_cafeomely2Layout = new javax.swing.GroupLayout(bg_cafeomely2);
        bg_cafeomely2.setLayout(bg_cafeomely2Layout);
        bg_cafeomely2Layout.setHorizontalGroup(
            bg_cafeomely2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_cafeomely2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(icon_cafe5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text_cafeomely5, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_cafeomely2Layout.setVerticalGroup(
            bg_cafeomely2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_cafe5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(text_cafeomely5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bg_chuquan2.add(bg_cafeomely2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 690, 50));

        bg_cafe_cake2.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout bg_cafe_cake2Layout = new javax.swing.GroupLayout(bg_cafe_cake2);
        bg_cafe_cake2.setLayout(bg_cafe_cake2Layout);
        bg_cafe_cake2Layout.setHorizontalGroup(
            bg_cafe_cake2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        bg_cafe_cake2Layout.setVerticalGroup(
            bg_cafe_cake2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        bg_chuquan2.add(bg_cafe_cake2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 470));

        bg_tracuuhd.add(bg_chuquan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 690, 560));

        javax.swing.GroupLayout home_tracuLayout = new javax.swing.GroupLayout(home_tracu.getContentPane());
        home_tracu.getContentPane().setLayout(home_tracuLayout);
        home_tracuLayout.setHorizontalGroup(
            home_tracuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_tracuuhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        home_tracuLayout.setVerticalGroup(
            home_tracuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_tracuuhd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg7.setBackground(new java.awt.Color(255, 255, 255));
        bg7.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bg7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_thoat.setBackground(new java.awt.Color(85, 65, 118));

        bg_trangchu7.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu7.setText("Bán hàng");

        icon_trangchu7.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_online_store_32px.png"))); // NOI18N
        icon_trangchu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu7.setOpaque(true);

        javax.swing.GroupLayout bg_trangchu7Layout = new javax.swing.GroupLayout(bg_trangchu7);
        bg_trangchu7.setLayout(bg_trangchu7Layout);
        bg_trangchu7Layout.setHorizontalGroup(
            bg_trangchu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_trangchu7Layout.createSequentialGroup()
                .addComponent(icon_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        bg_trangchu7Layout.setVerticalGroup(
            bg_trangchu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(icon_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        button_thoat.setBackground(new java.awt.Color(255, 255, 255));
        button_thoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat.setForeground(new java.awt.Color(204, 51, 0));
        button_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_back_arrow_30px.png"))); // NOI18N
        button_thoat.setText("Thoát");
        button_thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thoatLayout = new javax.swing.GroupLayout(bg_thoat);
        bg_thoat.setLayout(bg_thoatLayout);
        bg_thoatLayout.setHorizontalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addComponent(bg_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 759, Short.MAX_VALUE)
                .addComponent(button_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_thoatLayout.setVerticalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_thoat)
                .addContainerGap())
        );

        bg7.add(bg_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        bg_home_banhang.setBackground(new java.awt.Color(54, 33, 89));
        bg_home_banhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        them_hd.setBackground(new java.awt.Color(54, 33, 89));
        them_hd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg_home_banhang.add(them_hd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jTextField5.setBackground(new java.awt.Color(54, 33, 89));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Số lượng");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, 30));

        jTextField8.setBackground(new java.awt.Color(54, 33, 89));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Tên món");
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        sp_sl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sp_sl.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        bg_home_banhang.add(sp_sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 90, 30));

        txf_tongcong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txf_tongcong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bg_home_banhang.add(txf_tongcong, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 240, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("%");
        bg_home_banhang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, 50, 30));

        jTextField12.setBackground(new java.awt.Color(54, 33, 89));
        jTextField12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("%Giảm giá:");
        jTextField12.setBorder(null);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 120, 30));

        tx_giamgia.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tx_giamgia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bg_home_banhang.add(tx_giamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 50, 30));

        jTextField14.setBackground(new java.awt.Color(54, 33, 89));
        jTextField14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("Thanh toán:");
        jTextField14.setBorder(null);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 120, 30));

        tx_gia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_gia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx_gia.setEnabled(false);
        tx_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_giaActionPerformed(evt);
            }
        });
        bg_home_banhang.add(tx_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VND");
        bg_home_banhang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 50, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đơn Giá");
        bg_home_banhang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 100, 30));

        jTextField16.setBackground(new java.awt.Color(54, 33, 89));
        jTextField16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("Tổng cộng:");
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 120, 30));

        bt_them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/dong y.png"))); // NOI18N
        bt_them.setText("Thêm");
        bt_them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51), 2));
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });
        bg_home_banhang.add(bt_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 140, 40));

        cb_maban.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_maban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mabanActionPerformed(evt);
            }
        });
        bg_home_banhang.add(cb_maban, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 130, 30));

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_CTHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Mã bàn", "Tên món", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(jTable_CTHD);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1130, 210));

        jTextField9.setBackground(new java.awt.Color(85, 65, 118));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Thông tin chi tiết hóa đơn");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 300, 40));

        bg_home_banhang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1160, 270));

        jTextField10.setBackground(new java.awt.Color(54, 33, 89));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Mã bàn");
        jTextField10.setBorder(null);
        bg_home_banhang.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VND");
        bg_home_banhang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 50, 30));

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));

        themhd.setBackground(new java.awt.Color(204, 255, 204));

        icon_themhd.setBackground(new java.awt.Color(54, 33, 89));
        icon_themhd.setForeground(new java.awt.Color(255, 255, 255));
        icon_themhd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_themhd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/banhang/icons8_add_new_26px.png"))); // NOI18N
        icon_themhd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_themhd.setOpaque(true);

        bt_themhd.setBackground(new java.awt.Color(54, 33, 89));
        bt_themhd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_themhd.setForeground(new java.awt.Color(255, 255, 255));
        bt_themhd.setText("Thêm hóa đơn mới");
        bt_themhd.setOpaque(false);
        bt_themhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themhdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themhdLayout = new javax.swing.GroupLayout(themhd);
        themhd.setLayout(themhdLayout);
        themhdLayout.setHorizontalGroup(
            themhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themhdLayout.createSequentialGroup()
                .addComponent(icon_themhd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_themhd, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        themhdLayout.setVerticalGroup(
            themhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_themhd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(icon_themhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bt_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_thanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/icons8_cash_in_hand_40px.png"))); // NOI18N
        bt_thanhtoan.setText("Thanh toán");
        bt_thanhtoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        bt_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thanhtoanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Chức năng");

        bt_Xuathd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_Xuathd.setText("Xuất hóa đơn");
        bt_Xuathd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204)));
        bt_Xuathd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_XuathdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(themhd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bt_Xuathd, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bt_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_Xuathd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(themhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bg_home_banhang.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 620, -1));

        bt_bochon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_bochon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/icon/delete.png"))); // NOI18N
        bt_bochon.setText("Bỏ chọn");
        bt_bochon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 2));
        bt_bochon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bochonActionPerformed(evt);
            }
        });
        bg_home_banhang.add(bt_bochon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 130, 40));

        cb_makh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_makh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cb_makh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_makhActionPerformed(evt);
            }
        });
        bg_home_banhang.add(cb_makh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, 30));

        cb_tenmon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_tenmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tenmonActionPerformed(evt);
            }
        });
        bg_home_banhang.add(cb_tenmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 52, 160, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mã khách hàng");
        bg_home_banhang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 30));

        tx_thanhtoan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tx_thanhtoan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bg_home_banhang.add(tx_thanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 240, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("VND");
        bg_home_banhang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, 50, 30));

        bg7.add(bg_home_banhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1200, 510));

        bg_address.setBackground(new java.awt.Color(85, 65, 118));
        bg_address.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_cafeomely1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely1.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely1.setText("OMELY QUÁN ");
        bg_address.add(text_cafeomely1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 280, 56));

        icon_cafe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N
        bg_address.add(icon_cafe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        icon_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N
        bg_address.add(icon_cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 79, 56));

        bg7.add(bg_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_themhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themhdActionPerformed
           refresh();
    }//GEN-LAST:event_bt_themhdActionPerformed

    private void button_banhang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_banhang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_banhang2ActionPerformed

    private void button_thucdon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thucdon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_thucdon2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void bt_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thanhtoanActionPerformed
            DefaultTableModel model = (DefaultTableModel) jTable_CTHD.getModel();
            String tt = "";
            long kq = ThanhToan(model);
            String thanhtoan = tt.valueOf(kq);
            this.tx_thanhtoan.setText(tt.valueOf(thanhtoan));
            QuanLyBH_BLL ql = new QuanLyBH_BLL();

            String giamgia = ql.getGiamGia(this.cb_makh.getSelectedItem().toString());
            this.tx_giamgia.setText(giamgia);
            String maban = this.cb_maban.getSelectedItem().toString();
            this.bt_bochon.setEnabled(false);
            this.bt_them.setEnabled(false);
            long n_tt = Long.parseLong(thanhtoan);

            int n_giamgia = Integer.parseInt(giamgia);
            if (n_giamgia == 0) {
                this.txf_tongcong.setText(thanhtoan);
                boolean rs = ql.ThanhToan(maban, MaHD, this.txf_tongcong.getText());
                if (rs == true) {
                    JOptionPane.showMessageDialog(null, "Thanh toán thành công !", "Thông báo", JOptionPane.NO_OPTION);
                    return;
                }
                JOptionPane.showMessageDialog(null, "Thanh toán thất bại !", "Thông báo", JOptionPane.NO_OPTION);
                return;
            } else {
                float tongcong = n_tt - (n_tt *((float) n_giamgia / 100));

                String total = String.valueOf(tongcong);
                this.txf_tongcong.setText(total);
                boolean rs = ql.ThanhToan(MaHD, MaHD, total);
                if (rs == true) {
                    JOptionPane.showMessageDialog(null, "Thanh toán thành công !", "Thông báo", JOptionPane.NO_OPTION);
                    return;
                }
                JOptionPane.showMessageDialog(null, "Thanh toán thất bại !", "Thông báo", JOptionPane.NO_OPTION);
                return;
            }

    }//GEN-LAST:event_bt_thanhtoanActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thoatActionPerformed
        // TODO add your handling code here:
        home_banhang hbh = new home_banhang();
        hbh.setNguoigoi("Chu Quan");
        hbh.setTaiKhoan(TaiKhoan);
        hbh.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_button_thoatActionPerformed

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed

        String check = sp_sl.getValue().toString();
        if(check.equals("0"))
        {
            JOptionPane.showMessageDialog(null,"Số lượng phải lớn hơn 0 !", "Thông báo",JOptionPane.NO_OPTION);
            return;
        }
        else 
        {   
            if (cb_makh.isEnabled() == true && cb_maban.isEnabled() == true)
            {
                HoaDonDTO hd = new HoaDonDTO();
                CTHD_DTO cthd = new CTHD_DTO();
                QuanLyBH_BLL qlbh = new QuanLyBH_BLL();
                QuanLyNV_BLL qlnv = new QuanLyNV_BLL();

                hd.setMaKH(this.cb_makh.getSelectedItem().toString());
                hd.setMaNV(qlnv.getNhanVienBangTaiKhoan(this.TaiKhoan));
                hd.setNgayLap(getTimeNow());
                hd.setGiamGia(qlbh.getGiamGia(this.cb_makh.getSelectedItem().toString()));

                cthd.setMaBan(this.cb_maban.getSelectedItem().toString());
                cthd.setSL(sp_sl.getValue().toString());
                cthd.setMaMon(qlbh.getMaMon(this.cb_tenmon.getSelectedItem().toString()));
                
                MaHD = qlbh.ThemHD(hd, cthd);
                
                if(MaHD!=null)
                {
                    JOptionPane.showMessageDialog(null,"Thêm hóa đơn mới, cthd thành công !", "Thông báo",JOptionPane.NO_OPTION);
                    DefaultTableModel model = (DefaultTableModel)jTable_CTHD.getModel();
                    Object[] data = new Object[6];
                    data[0] = MaHD;        
                    data[1] = cb_makh.getSelectedItem().toString();
                    data[2] = cb_maban.getSelectedItem().toString();
                    data[3] = cb_tenmon.getSelectedItem().toString();
                    data[4] = sp_sl.getValue();
                    data[5] = tx_gia.getText();
                    model.addRow(data);

                    this.cb_makh.setEnabled(false);
                    this.cb_maban.setEnabled(false);
                    return;
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Thêm hóa đơn mới, cthd không thành công !", "Thông báo",JOptionPane.NO_OPTION);
                    return;
                }   
            }
            else
            {
                DefaultTableModel model = (DefaultTableModel)jTable_CTHD.getModel();
                String tenmon = this.cb_tenmon.getSelectedItem().toString();

                for(int i = 0; i < model.getRowCount();i++ )
                {
                    if(tenmon.equals(model.getValueAt(i, 3)))
                    {
                        JOptionPane.showMessageDialog(null,"Khách hàng này đã chọn món này rồi !", "Thông báo",JOptionPane.NO_OPTION);
                        return;
                    }
                }
                
                CTHD_DTO cthd = new CTHD_DTO();
                QuanLyBH_BLL qlbh = new QuanLyBH_BLL();
                cthd.setMaHD(MaHD);
                cthd.setMaKH(this.cb_makh.getSelectedItem().toString());
                cthd.setMaBan(this.cb_maban.getSelectedItem().toString());
                cthd.setSL(sp_sl.getValue().toString());
                cthd.setMaMon(qlbh.getMaMon(this.cb_tenmon.getSelectedItem().toString()));
                
                boolean kq = qlbh.ThemCTHD(cthd); 
                if(kq == true)
                {
                    JOptionPane.showMessageDialog(null,"Thêm cthd thành công !", "Thông báo",JOptionPane.NO_OPTION);
                    Object[] data = new Object[6];
                    data[0] = MaHD;        
                    data[1] = cb_makh.getSelectedItem().toString();
                    data[2] = cb_maban.getSelectedItem().toString();
                    data[3] = cb_tenmon.getSelectedItem().toString();
                    data[4] = sp_sl.getValue();
                    data[5] = tx_gia.getText();
                    model.addRow(data);
                    return;
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Thêm cthd không thành công !", "Thông báo",JOptionPane.NO_OPTION);
                    return;
                }
            }
            
            
        }
    }//GEN-LAST:event_bt_themActionPerformed

    private void bt_bochonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bochonActionPerformed

        DefaultTableModel model = (DefaultTableModel)jTable_CTHD.getModel();
        //Delete Selected Row  
        int choose = -1;
        choose = jTable_CTHD.getSelectedRow();
        
        //Check if their is a row selected
        if (choose < 0) 
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa chọn dòng nào để bỏ chọn !", "Thông báo",JOptionPane.NO_OPTION);
            return;
        } 
        else 
        {
            QuanLyBH_BLL ql = new QuanLyBH_BLL();
            boolean kq = ql.Xoa_CTHD(model.getValueAt(choose, 0).toString());
            if(kq==true)
            {
                model.removeRow(choose);
                JOptionPane.showMessageDialog(null,"Bạn vừa bỏ 1 lựa chọn của khách hàng và xóa bỏ cthd !", "Thông báo",JOptionPane.NO_OPTION);
                return;
            }
            JOptionPane.showMessageDialog(null,"Lỗi xóa bỏ CTHD !", "Thông báo",JOptionPane.NO_OPTION);
            return;
        }
    }//GEN-LAST:event_bt_bochonActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void cb_makhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_makhActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cb_makhActionPerformed

    private void cb_mabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mabanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_mabanActionPerformed

    private void cb_tenmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tenmonActionPerformed

        this.tx_gia.setText(LoadDonGia(this.cb_tenmon.getSelectedItem().toString()));
        this.tx_gia.setEnabled(false);
        
    }//GEN-LAST:event_cb_tenmonActionPerformed

    private void tx_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_giaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tx_giaActionPerformed

    private void bt_XuathdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_XuathdActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable_CTHD.getModel();
        String MAHD = null;
        MAHD = (String) model.getValueAt(0, 0);
        
        if(MAHD == null)
        {
            JOptionPane.showMessageDialog(null,"Chưa có hóa đơn nào, không xuất hóa đơn được !", "Thông báo",JOptionPane.NO_OPTION);
            return;
        }
        
        HashMap parameters = new HashMap();
        parameters.put("MAHD", MAHD);       
        Connection con = Database.conectionJDBC();
        String dir = "C:\\coffee_shop\\src\\Report\\PhieuThanhToan.jrxml";

        try {
            JasperDesign jd = JRXmlLoader.load(dir);
            JasperReport jr  = JasperCompileManager.compileReport(dir);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameters, con);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(tao_hd.class.getName()).log(Level.SEVERE, null, ex);
        }


        
    }//GEN-LAST:event_bt_XuathdActionPerformed

    public void setComBoBox()
    {
        LoadCBB("MaKH");
        LoadCBB("MaBan");
        LoadCBB("dfasdf");
        return;
    }
    
    public void LoadCBB(String str)
    {

        try 
        {
            QuanLyBH_BLL ql = new QuanLyBH_BLL();
            ResultSet rs = ql.Check(str);
            while(rs.next())
            {
                if(str.equals("MaKH"))
                    cb_makh.addItem(rs.getString(1));
                else 
                {
                    if(str.equals("MaBan"))
                        cb_maban.addItem(rs.getString(1));
                    else
                        cb_tenmon.addItem(rs.getString(1));
                }
            }
            return;
        } catch (SQLException ex) {
            Logger.getLogger(tao_hd.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Tải dữ liệu lên CBB bị lỗi!", "Thông báo",JOptionPane.NO_OPTION);
            return;
        }
    }
    public String LoadDonGia(String str)
    {
        QuanLyBH_BLL ql = new QuanLyBH_BLL();
        return ql.LoadDonGia(str);
    }
    
    public String getTimeNow()
    {
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
        Calendar cal = Calendar.getInstance();
        String time = dateFormat.format(cal.getTime()).toUpperCase();
        return time;
    }
    
    public long ThanhToan(DefaultTableModel model)
    {
        long total = 0;
        for(int i = 0; i < model.getRowCount(); i++)
        {
           long n1 = Long.parseLong((model.getValueAt(i, 4)).toString());
           long n2 = Long.parseLong((model.getValueAt(i, 5)).toString());
           total = (n1*n2) + total;
        }
        return total;
    }
    
    public void refresh()
    {
        this.cb_makh.setEnabled(true);
        this.cb_maban.setEnabled(true);

        this.cb_tenmon.setSelectedIndex(0);
        this.sp_sl.setValue(0);
        
        this.tx_thanhtoan.setText(null);
        
        this.tx_giamgia.setText(null);
        
        this.txf_tongcong.setText(null);
        
        DefaultTableModel model = new DefaultTableModel();
        String[] title = {"Mã hóa đơn", "Mã khách hàng", "Mã bàn", "Tên món", "Số lượng", "Đơn giá"};
        model.setColumnIdentifiers(title);
        
        this.jTable_CTHD.setModel(model);
        
        this.cb_makh.setSelectedIndex(0);
        this.cb_maban.setSelectedIndex(0);
        
        this.bt_bochon.setEnabled(true);
        this.bt_them.setEnabled(true);
        return;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tao_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tao_hd().setVisible(true);

            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg7;
    private javax.swing.JPanel bg_address;
    private javax.swing.JPanel bg_address2;
    private javax.swing.JPanel bg_banhang2;
    private javax.swing.JPanel bg_cafe_cake2;
    private javax.swing.JPanel bg_cafeomely2;
    private javax.swing.JPanel bg_chuquan2;
    private javax.swing.JPanel bg_home_banhang;
    private javax.swing.JPanel bg_thoat;
    private javax.swing.JPanel bg_thoat2;
    private javax.swing.JPanel bg_thucdon2;
    private javax.swing.JPanel bg_tracuuhd;
    private javax.swing.JPanel bg_trangchu7;
    private javax.swing.JPanel bg_trangchu9;
    private javax.swing.JButton bt_Xuathd;
    private javax.swing.JButton bt_bochon;
    private javax.swing.JButton bt_thanhtoan;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_themhd;
    private javax.swing.JButton button_banhang2;
    private javax.swing.JButton button_thoat;
    private javax.swing.JButton button_thoat2;
    private javax.swing.JButton button_thucdon2;
    private javax.swing.JComboBox<String> cb_maban;
    private javax.swing.JComboBox<String> cb_makh;
    private javax.swing.JComboBox<String> cb_tenmon;
    private javax.swing.JFrame home_tracu;
    private javax.swing.JLabel icon_banhang2;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_cafe1;
    private javax.swing.JLabel icon_cafe4;
    private javax.swing.JLabel icon_cafe5;
    private javax.swing.JLabel icon_themhd;
    private javax.swing.JLabel icon_thucdon2;
    private javax.swing.JLabel icon_trangchu7;
    private javax.swing.JLabel icon_trangchu9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_CTHD;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel sidepane9;
    private javax.swing.JSpinner sp_sl;
    private javax.swing.JLabel text_cafeomely1;
    private javax.swing.JLabel text_cafeomely4;
    private javax.swing.JLabel text_cafeomely5;
    private javax.swing.JLabel text_trangchu7;
    private javax.swing.JLabel text_trangchu9;
    private javax.swing.JPanel them_hd;
    private javax.swing.JPanel themhd;
    private javax.swing.JTextField tx_gia;
    private javax.swing.JTextField tx_giamgia;
    private javax.swing.JTextField tx_thanhtoan;
    private javax.swing.JTextField txf_tongcong;
    // End of variables declaration//GEN-END:variables
}
