/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doan;

import BLL.QuanLyBH_BLL;
import BLL.QuanLyNV_BLL;
import DAL.Database;
import DTO.HoaDonDTO;
import DTO.NhanVienDTO;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MSI2
 */
public class tra_cuu_hd extends javax.swing.JFrame {

    
    private String TaiKhoan;

    public String getTaiKhoan() {
        return TaiKhoan;
    }

    public void setTaiKhoan(String TaiKhoan) {
        this.TaiKhoan = TaiKhoan;
    }
    
    /**
     * Creates new form tra_cuu_hd
     */
    public tra_cuu_hd() {
        initComponents();
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PMenu = new javax.swing.JPopupMenu();
        cthd = new javax.swing.JMenuItem();
        bg7 = new javax.swing.JPanel();
        bg_thoat = new javax.swing.JPanel();
        bg_trangchu7 = new javax.swing.JPanel();
        text_trangchu7 = new javax.swing.JLabel();
        icon_trangchu7 = new javax.swing.JLabel();
        button_thoat = new javax.swing.JButton();
        bg_home_banhang = new javax.swing.JPanel();
        bg_cafe_cake = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_hd = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        text_search = new javax.swing.JTextField();
        gachchan = new javax.swing.JPanel();
        bt_tim = new javax.swing.JButton();
        them_hd = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        bg_address = new javax.swing.JPanel();
        text_cafeomely1 = new javax.swing.JLabel();
        icon_cafe1 = new javax.swing.JLabel();
        icon_cafe = new javax.swing.JLabel();
        text_cafeomely = new javax.swing.JLabel();

        cthd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cthd.setForeground(new java.awt.Color(0, 255, 51));
        cthd.setText("Chi tiết hóa đơn");
        PMenu.add(cthd);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg7.setBackground(new java.awt.Color(255, 255, 255));
        bg7.setMaximumSize(new java.awt.Dimension(1280, 1000));
        bg7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_thoat.setBackground(new java.awt.Color(85, 65, 118));

        bg_trangchu7.setBackground(new java.awt.Color(85, 65, 118));

        text_trangchu7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        text_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        text_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu7.setText("Bán hàng");

        icon_trangchu7.setBackground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setForeground(new java.awt.Color(255, 255, 255));
        icon_trangchu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_online_store_32px.png"))); // NOI18N
        icon_trangchu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        icon_trangchu7.setOpaque(true);

        javax.swing.GroupLayout bg_trangchu7Layout = new javax.swing.GroupLayout(bg_trangchu7);
        bg_trangchu7.setLayout(bg_trangchu7Layout);
        bg_trangchu7Layout.setHorizontalGroup(
            bg_trangchu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_trangchu7Layout.createSequentialGroup()
                .addComponent(icon_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        bg_trangchu7Layout.setVerticalGroup(
            bg_trangchu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(icon_trangchu7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        button_thoat.setBackground(new java.awt.Color(255, 255, 255));
        button_thoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        button_thoat.setForeground(new java.awt.Color(204, 51, 0));
        button_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_back_arrow_30px.png"))); // NOI18N
        button_thoat.setText("Thoát");
        button_thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        button_thoat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        button_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_thoatLayout = new javax.swing.GroupLayout(bg_thoat);
        bg_thoat.setLayout(bg_thoatLayout);
        bg_thoatLayout.setHorizontalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addComponent(bg_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 759, Short.MAX_VALUE)
                .addComponent(button_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_thoatLayout.setVerticalGroup(
            bg_thoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg_trangchu7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_thoatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_thoat)
                .addContainerGap())
        );

        bg7.add(bg_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        bg_home_banhang.setBackground(new java.awt.Color(54, 33, 89));
        bg_home_banhang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg_cafe_cake.setBackground(new java.awt.Color(85, 65, 118));

        tb_hd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tb_hd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Thành tiền", "Ngày lập", "Mã nhân viên", "Giảm giá", "Trạng thái"
            }
        ));
        tb_hd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hdMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_hdMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tb_hd);

        jLabel2.setBackground(new java.awt.Color(85, 65, 118));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kết quả tra cứu hóa đơn");

        javax.swing.GroupLayout bg_cafe_cakeLayout = new javax.swing.GroupLayout(bg_cafe_cake);
        bg_cafe_cake.setLayout(bg_cafe_cakeLayout);
        bg_cafe_cakeLayout.setHorizontalGroup(
            bg_cafe_cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
            .addGroup(bg_cafe_cakeLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg_cafe_cakeLayout.setVerticalGroup(
            bg_cafe_cakeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_cafe_cakeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        bg_home_banhang.add(bg_cafe_cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1180, 310));

        search.setBackground(new java.awt.Color(85, 65, 118));
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_search.setBackground(new java.awt.Color(85, 65, 118));
        text_search.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        text_search.setForeground(new java.awt.Color(255, 255, 255));
        text_search.setBorder(null);
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });
        search.add(text_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        javax.swing.GroupLayout gachchanLayout = new javax.swing.GroupLayout(gachchan);
        gachchan.setLayout(gachchanLayout);
        gachchanLayout.setHorizontalGroup(
            gachchanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gachchanLayout.setVerticalGroup(
            gachchanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        search.add(gachchan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 1));

        bt_tim.setBackground(new java.awt.Color(54, 33, 89));
        bt_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/banhang/icons8_search_26px.png"))); // NOI18N
        bt_tim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        bt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timActionPerformed(evt);
            }
        });
        search.add(bt_tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        bg_home_banhang.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 200, 40));

        them_hd.setBackground(new java.awt.Color(54, 33, 89));
        them_hd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg_home_banhang.add(them_hd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jTextField10.setBackground(new java.awt.Color(54, 33, 89));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Nhập mã hóa đơn:");
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        bg_home_banhang.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, 40));

        bg7.add(bg_home_banhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1200, 510));

        bg_address.setBackground(new java.awt.Color(85, 65, 118));
        bg_address.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_cafeomely1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        text_cafeomely1.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely1.setText("OMELY QUÁN ");
        bg_address.add(text_cafeomely1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 280, 56));

        icon_cafe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/dangnhap/icons8_cafe_50px.png"))); // NOI18N
        bg_address.add(icon_cafe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        icon_cafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doan/images/chuquan/icons8_address_50px_1.png"))); // NOI18N
        bg_address.add(icon_cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 60, 50));

        text_cafeomely.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_cafeomely.setForeground(new java.awt.Color(255, 255, 255));
        text_cafeomely.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_cafeomely.setText("Đ/C: Thị trấn Phú Phong, huyện Tây Sơn, tỉnh Bình Định.");
        bg_address.add(text_cafeomely, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 523, 50));

        bg7.add(bg_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_searchActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void button_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thoatActionPerformed
        // TODO add your handling code here:
        home_banhang hbh = new home_banhang();
        hbh.setNguoigoi("Chu Quan");
        hbh.setTaiKhoan(TaiKhoan);
        hbh.setVisible(true);
        this.dispose();
        return;
    }//GEN-LAST:event_button_thoatActionPerformed

    private void tb_hdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hdMouseReleased
       
        DefaultTableModel model = (DefaultTableModel)tb_hd.getModel();
        int choose = -1;
        choose = tb_hd.getSelectedRow();
        
        if(evt.getButton()== 3)
        {
            if(choose == -1)
            {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn một hóa đơn cần xem thông tin.","Thông báo", JOptionPane.NO_OPTION);
                return;
            }
            JPopupMenu a = new JPopupMenu();
            JMenuItem b = new JMenuItem("   Xem chi tiết hóa đơn  ");
            b.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            String MAHD = (String) model.getValueAt(choose, 0);
            b.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    HashMap parameters = new HashMap();
                    parameters.put("MAHD", MAHD);       
                    Connection con = Database.conectionJDBC();
                    String dir = "F:\\iReport\\Report\\PhieuThanhToan.jrxml";

                    try {
                        JasperDesign jd = JRXmlLoader.load(dir);
                    } catch (JRException ex) {
                        Logger.getLogger(tao_hd.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JasperReport jr = null;
                    try {
                        jr = JasperCompileManager.compileReport(dir);
                    } catch (JRException ex) {
                        Logger.getLogger(tao_hd.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JasperPrint jp = null;
                    try {   
                        jp = JasperFillManager.fillReport(jr, parameters, con);
                    } catch (JRException ex) {
                        Logger.getLogger(tao_hd.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JasperViewer jv = new JasperViewer(jp, false);
                    jv.setVisible(true);
                    
                }
            });
            a.add(b);
            a.show(evt.getComponent(), evt.getX(), evt.getY());
        }
        
    }//GEN-LAST:event_tb_hdMouseReleased

    private void bt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timActionPerformed
        // TODO add your handling code here:
        
        if(text_search.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã hóa đơn","Thông báo", JOptionPane.NO_OPTION);
            return;
        }
        QuanLyBH_BLL ql = new QuanLyBH_BLL();
        DefaultTableModel model = new DefaultTableModel();
        String[] title = {"Mã hóa đơn", "Mã khách hàng", "Thành tiền", "Ngày lập", "Mã nhân viên", "Giảm giá","Trạng thái"};
        model.setColumnIdentifiers(title);
        HoaDonDTO hd = ql.getHD(this.text_search.getText());
        
        String MaHD = hd.getMaHD();
        String MaKH = hd.getMaKH();
        String ThanhTien = hd.getThanhTien();
        String NgayLap = hd.getNgayLap();
        String MaNV = hd.getMaNV();
        String Giamgia = hd.getGiamGia();
        String TrangThai = hd.getTrangthai();
        Object[] temp = {MaHD, MaKH, ThanhTien, NgayLap, MaNV, Giamgia, TrangThai};
        model.addRow(temp);

        Object value = model.getValueAt(0,0);
        if (value == null)
        {
                JOptionPane.showMessageDialog(null, "Không có kết quả cần tìm!");
                return;
        }
                
        this.tb_hd.setModel(model);
        return;
        
    }//GEN-LAST:event_bt_timActionPerformed

    private void tb_hdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_hdMouseClicked

    public void setTable()
    {
        QuanLyBH_BLL ql = new QuanLyBH_BLL();
        DefaultTableModel model = new DefaultTableModel();
        String[] title = {"Mã hóa đơn", "Mã khách hàng", "Thành tiền", "Ngày lập", "Mã nhân viên", "Giảm giá","Trạng thái"};
        model.setColumnIdentifiers(title);
        ArrayList<HoaDonDTO> ar = ql.getAllHD();
        for(int i=0;i < ar.size();i++)
        {
            HoaDonDTO hd = ar.get(i);
            String MaHD = hd.getMaHD();
            String MaKH = hd.getMaKH();
            String ThanhTien = hd.getThanhTien();
            String NgayLap = hd.getNgayLap();
            String MaNV = hd.getMaNV();
            String Giamgia = hd.getGiamGia();
            String TrangThai = hd.getTrangthai();
            Object[]temp={MaHD, MaKH, ThanhTien, NgayLap, MaNV, Giamgia, TrangThai};
            model.addRow(temp);
        }
        this.tb_hd.setModel(model);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tra_cuu_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tra_cuu_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tra_cuu_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tra_cuu_hd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tra_cuu_hd().setVisible(true);
            }
        });
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PMenu;
    private javax.swing.JPanel bg7;
    private javax.swing.JPanel bg_address;
    private javax.swing.JPanel bg_cafe_cake;
    private javax.swing.JPanel bg_home_banhang;
    private javax.swing.JPanel bg_thoat;
    private javax.swing.JPanel bg_trangchu7;
    private javax.swing.JButton bt_tim;
    private javax.swing.JButton button_thoat;
    private javax.swing.JMenuItem cthd;
    private javax.swing.JPanel gachchan;
    private javax.swing.JLabel icon_cafe;
    private javax.swing.JLabel icon_cafe1;
    private javax.swing.JLabel icon_trangchu7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JPanel search;
    private javax.swing.JTable tb_hd;
    private javax.swing.JLabel text_cafeomely;
    private javax.swing.JLabel text_cafeomely1;
    private javax.swing.JTextField text_search;
    private javax.swing.JLabel text_trangchu7;
    private javax.swing.JPanel them_hd;
    // End of variables declaration//GEN-END:variables
}
